const skillBank = ["python", "sql", "excel", "power bi", "tableau", "javascript", "html", "css", "react", "java", "c++", "machine learning", "data analysis", "data visualization", "communication", "leadership", "project management", "aws", "azure", "docker", "git", "figma", "salesforce", "marketing", "accounting", "finance", "recruitment", "customer service"];
const educationWords = ["bachelor", "b.tech", "b.e.", "bsc", "master", "m.tech", "mba", "msc", "phd", "degree"];
let candidates = [];
let lastRanked = [];

function text(id) { return document.getElementById(id).value.trim(); }
function findTerms(value, terms) { const lower = value.toLowerCase(); return terms.filter(term => lower.includes(term)); }
function jobCriteria() { const jd = text("jobDescription"); return { skills: findTerms(jd, skillBank), education: findTerms(jd, educationWords), years: (jd.match(/\b(\d+)\+?\s*(?:years?|yrs?)/i) || [])[1] }; }
function weights() { return { skills: Number(text("skillsWeight")), experience: Number(text("experienceWeight")), education: Number(text("educationWeight")) }; }
function validWeights() { const total = Object.values(weights()).reduce((sum, value) => sum + value, 0), message = document.getElementById("weightMessage"); message.textContent = total === 100 ? "Total: 100% ✓" : `Total: ${total}% — please make it 100%.`; message.classList.toggle("invalid", total !== 100); return total === 100; }
function showCriteria() { const criteria = jobCriteria(), target = document.getElementById("criteria"); if (!text("jobDescription")) { alert("Please paste a job description first."); return; } target.classList.remove("hidden"); target.innerHTML = `<strong>Criteria found:</strong><br>${criteria.skills.length ? criteria.skills.map(s => `<span class="tag">${s}</span>`).join("") : "No common skills found—try adding skill names."}${criteria.years ? `<span class="tag">${criteria.years}+ years experience</span>` : ""}`; }
function addCandidate() { const name = text("candidateName"), resume = text("resumeText"); if (!name || !resume) { alert("Please enter both a candidate name and resume text."); return; } candidates.push({ name, resume }); document.getElementById("candidateName").value = ""; document.getElementById("resumeText").value = ""; renderCandidates(); }
function renderCandidates() { document.getElementById("candidateList").innerHTML = candidates.map((c, i) => `<div class="candidate-chip"><span>${c.name}</span><button class="remove" onclick="removeCandidate(${i})">Remove</button></div>`).join(""); }
function removeCandidate(i) { candidates.splice(i, 1); renderCandidates(); lastRanked = []; document.getElementById("exportCsv").disabled = true; document.getElementById("results").innerHTML = "Candidates changed. Click Rank candidates again."; }
function score(candidate, criteria, selectedWeights) { const found = findTerms(candidate.resume, criteria.skills), missing = criteria.skills.filter(skill => !found.includes(skill)); const skillScore = criteria.skills.length ? (found.length / criteria.skills.length) * selectedWeights.skills : 0; const educationScore = criteria.education.length && findTerms(candidate.resume, criteria.education).length ? selectedWeights.education : 0; const listedYears = (candidate.resume.match(/\b(\d+)\+?\s*(?:years?|yrs?)/i) || [])[1]; const experienceScore = criteria.years && listedYears ? Math.min(Number(listedYears) / Number(criteria.years), 1) * selectedWeights.experience : 0; return { value: Math.round(skillScore + educationScore + experienceScore), found, missing, experience: listedYears || "Not stated" }; }
function rankCandidates() { const criteria = jobCriteria(), output = document.getElementById("results"); if (!text("jobDescription") || !candidates.length) { alert("Add a job description and at least one candidate first."); return; } if (!criteria.skills.length) { alert("Please include at least one skill from the job description, such as Python, SQL, or Excel."); return; } if (!validWeights()) { alert("Your score weights must add up to 100%."); return; } lastRanked = candidates.map(c => ({ ...c, ...score(c, criteria, weights()) })).sort((a, b) => b.value - a.value); output.classList.remove("empty-state"); output.innerHTML = lastRanked.map((c, i) => `<div class="result-row"><div class="rank">#${i + 1}</div><div><strong>${c.name}</strong><div class="bar"><div class="fill" style="width:${c.value}%"></div></div><div class="match">Matched: ${c.found.join(", ") || "No listed skills"}</div><div class="match missing">Missing: ${c.missing.join(", ") || "No listed skills missing"}</div></div><div class="score">${c.value}% match</div></div>`).join("") + `<div class="fairness"><strong>Human review required:</strong> This is a simple keyword comparison, not an automated hiring decision. Check each resume fairly, consider transferable skills, and never use protected personal characteristics to rank people.</div>`; document.getElementById("exportCsv").disabled = false; }
function loadSample() { document.getElementById("jobDescription").value = "Data Analyst needed with Python, SQL, Excel, Power BI, data analysis and communication skills. A bachelor's degree and 2 years of experience are preferred."; candidates = [{ name: "Ananya Sharma", resume: "Bachelor's degree in Computer Science. 3 years of experience as a Data Analyst using Python, SQL, Excel, Power BI and data analysis. Strong communication skills." }, { name: "Rahul Verma", resume: "BSc graduate with 2 years of experience in SQL, Excel, Tableau and data visualization. Good communication and project management skills." }, { name: "Meera Iyer", resume: "Bachelor degree in Statistics. Intern with Python, Excel, machine learning and data analysis projects. Strong presentation skills." }]; renderCandidates(); showCriteria(); document.getElementById("results").classList.add("empty-state"); document.getElementById("results").textContent = "Sample role and candidates loaded. Click Rank candidates to see the results."; }
function exportCsv() { if (!lastRanked.length) return; const rows = [["Rank", "Candidate", "Match score", "Matched skills", "Missing skills", "Stated experience"], ...lastRanked.map((c, index) => [index + 1, c.name, `${c.value}%`, c.found.join("; "), c.missing.join("; "), c.experience])]; const csv = rows.map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = "talentlens-candidate-ranking.csv"; link.click(); URL.revokeObjectURL(link.href); }
document.getElementById("analyzeJob").addEventListener("click", showCriteria); document.getElementById("addCandidate").addEventListener("click", addCandidate); document.getElementById("loadSample").addEventListener("click", loadSample); document.getElementById("rankCandidates").addEventListener("click", rankCandidates); document.getElementById("exportCsv").addEventListener("click", exportCsv); document.querySelectorAll(".weight-input").forEach(input => input.addEventListener("input", validWeights)); document.getElementById("resumeFile").addEventListener("change", e => { const file = e.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = event => document.getElementById("resumeText").value = event.target.result; reader.readAsText(file); });
