const skillBank = ["python", "sql", "excel", "power bi", "tableau", "javascript", "html", "css", "react", "java", "c++", "machine learning", "data analysis", "data visualization", "communication", "leadership", "project management", "aws", "azure", "docker", "git", "figma", "salesforce", "marketing", "accounting", "finance", "recruitment", "customer service"];
const educationWords = ["bachelor", "b.tech", "b.e.", "bsc", "master", "m.tech", "mba", "msc", "phd", "degree"];
let candidates = [];
let lastRanked = [];

if (window.pdfjsLib) { pdfjsLib.GlobalWorkerOptions.workerSrc = "https://unpkg.com/pdfjs-dist@3.11.174/build/pdf.worker.min.js"; }

function text(id) { return document.getElementById(id).value.trim(); }
function customSkillList() { return text("customSkills").split(",").map(skill => skill.trim().toLowerCase()).filter(Boolean); }
function findTerms(value, terms) { const lower = value.toLowerCase(); return terms.filter(term => lower.includes(term)); }
function jobCriteria() { const jd = text("jobDescription"); const combinedSkills = [...new Set([...findTerms(jd, skillBank), ...customSkillList()])]; return { skills: combinedSkills, education: findTerms(jd, educationWords), years: (jd.match(/\b(\d+)\+?\s*(?:years?|yrs?)/i) || [])[1] }; }
function weights() { return { skills: Number(text("skillsWeight")), experience: Number(text("experienceWeight")), education: Number(text("educationWeight")) }; }
function validWeights() { const total = Object.values(weights()).reduce((sum, value) => sum + value, 0), message = document.getElementById("weightMessage"); message.textContent = total === 100 ? "Total: 100% ✓" : `Total: ${total}% — please make it 100%.`; message.classList.toggle("invalid", total !== 100); return total === 100; }
function showCriteria() { const criteria = jobCriteria(), target = document.getElementById("criteria"); if (!text("jobDescription")) { alert("Please paste a job description first."); return; } target.classList.remove("hidden"); target.innerHTML = `<strong>Criteria found:</strong><br>${criteria.skills.length ? criteria.skills.map(s => `<span class="tag">${s}</span>`).join("") : "No common skills found—try adding skill names."}${criteria.years ? `<span class="tag">${criteria.years}+ years experience</span>` : ""}`; }
function addCandidate() { const name = text("candidateName"), resume = text("resumeText"); if (!name || !resume) { alert("Please enter both a candidate name and resume text."); return; } candidates.push({ name, resume }); document.getElementById("candidateName").value = ""; document.getElementById("resumeText").value = ""; clearResults(); renderCandidates(); }
function renderCandidates() { document.getElementById("candidateList").innerHTML = candidates.map((c, i) => `<div class="candidate-chip"><span>${c.name}</span><button class="remove" onclick="removeCandidate(${i})">Remove</button></div>`).join(""); }
function clearResults(message = "Candidates changed. Click Rank candidates again.") { lastRanked = []; document.getElementById("exportCsv").disabled = true; document.getElementById("summary").classList.add("hidden"); document.getElementById("chart").classList.add("hidden"); document.getElementById("chart").innerHTML = ""; document.getElementById("results").className = "results empty-state"; document.getElementById("results").textContent = message; }
function removeCandidate(i) { candidates.splice(i, 1); renderCandidates(); clearResults(); }
function score(candidate, criteria, selectedWeights) { const found = findTerms(candidate.resume, criteria.skills), missing = criteria.skills.filter(skill => !found.includes(skill)); const skillScore = criteria.skills.length ? (found.length / criteria.skills.length) * selectedWeights.skills : 0; const educationScore = criteria.education.length && findTerms(candidate.resume, criteria.education).length ? selectedWeights.education : 0; const listedYears = (candidate.resume.match(/\b(\d+)\+?\s*(?:years?|yrs?)/i) || [])[1]; const experienceScore = criteria.years && listedYears ? Math.min(Number(listedYears) / Number(criteria.years), 1) * selectedWeights.experience : 0; return { value: Math.round(skillScore + educationScore + experienceScore), found, missing, experience: listedYears || "Not stated", skillScore: Math.round(skillScore), educationScore: Math.round(educationScore), experienceScore: Math.round(experienceScore) }; }
function filteredResults() { const nameFilter = text("resultFilter").toLowerCase(); const minScore = Number(text("minScoreFilter")) || 0; const minExperience = Number(text("minExperienceFilter")) || 0; return lastRanked.filter(candidate => { const years = Number(candidate.experience) || 0; return candidate.name.toLowerCase().includes(nameFilter) && candidate.value >= minScore && years >= minExperience; }); }
function renderResults() { const output = document.getElementById("results"), nameFilter = text("resultFilter"), shown = filteredResults(); output.classList.remove("empty-state"); output.innerHTML = shown.length ? shown.map(candidate => `<div class="result-row"><div class="rank">#${lastRanked.indexOf(candidate) + 1}</div><div><strong>${candidate.name}</strong><div class="bar"><div class="fill" style="width:${candidate.value}%"></div></div><div class="match">Matched: ${candidate.found.join(", ") || "No listed skills"}</div><div class="match missing">Missing: ${candidate.missing.join(", ") || "No listed skills missing"}</div><div class="breakdown">Score breakdown — Skills: ${candidate.skillScore}% · Experience: ${candidate.experienceScore}% · Education: ${candidate.educationScore}%</div></div><div class="score">${candidate.value}% match</div></div>`).join("") : "No candidate matches those filters."; if (!nameFilter) output.innerHTML += `<div class="fairness"><strong>Human review required:</strong> This is a simple keyword comparison, not an automated hiring decision. Check each resume fairly, consider transferable skills, and never use protected personal characteristics to rank people.</div>`; renderChart(shown); }
function renderChart(shown) { const chart = document.getElementById("chart"); if (!shown.length) { chart.classList.add("hidden"); chart.innerHTML = ""; return; } chart.classList.remove("hidden"); chart.innerHTML = `<h3>Score comparison</h3>` + shown.map(candidate => `<div class="chart-row"><span class="chart-label">${candidate.name}</span><div class="chart-bar"><div class="chart-segment skills" style="width:${candidate.skillScore}%" title="Skills: ${candidate.skillScore}%"></div><div class="chart-segment experience" style="width:${candidate.experienceScore}%" title="Experience: ${candidate.experienceScore}%"></div><div class="chart-segment education" style="width:${candidate.educationScore}%" title="Education: ${candidate.educationScore}%"></div></div><span class="chart-value">${candidate.value}%</span></div>`).join("") + `<div class="chart-legend"><span><i class="dot skills"></i>Skills</span><span><i class="dot experience"></i>Experience</span><span><i class="dot education"></i>Education</span></div>`; }
function updateSummary() { const total = lastRanked.length, average = Math.round(lastRanked.reduce((sum, candidate) => sum + candidate.value, 0) / total), top = lastRanked[0]; const summary = document.getElementById("summary"); summary.classList.remove("hidden"); summary.innerHTML = `<div class="stat"><span>CANDIDATES</span><strong>${total}</strong></div><div class="stat"><span>AVERAGE MATCH</span><strong>${average}%</strong></div><div class="stat"><span>TOP MATCH</span><strong>${top.name} (${top.value}%)</strong></div>`; }
function rankCandidates() { const criteria = jobCriteria(), output = document.getElementById("results"); if (!text("jobDescription") || !candidates.length) { alert("Add a job description and at least one candidate first."); return; } if (!criteria.skills.length) { alert("Please include at least one skill from the job description, such as Python, SQL, or Excel."); return; } if (!validWeights()) { alert("Your score weights must add up to 100%."); return; } lastRanked = candidates.map(c => ({ ...c, ...score(c, criteria, weights()) })).sort((a, b) => b.value - a.value); output.classList.remove("empty-state"); updateSummary(); renderResults(); document.getElementById("exportCsv").disabled = false; }
function loadSample() { document.getElementById("jobDescription").value = "Data Analyst needed with Python, SQL, Excel, Power BI, data analysis and communication skills. A bachelor's degree and 2 years of experience are preferred."; candidates = [{ name: "Ananya Sharma", resume: "Bachelor's degree in Computer Science. 3 years of experience as a Data Analyst using Python, SQL, Excel, Power BI and data analysis. Strong communication skills." }, { name: "Rahul Verma", resume: "BSc graduate with 2 years of experience in SQL, Excel, Tableau and data visualization. Good communication and project management skills." }, { name: "Meera Iyer", resume: "Bachelor degree in Statistics. Intern with Python, Excel, machine learning and data analysis projects. Strong presentation skills." }]; renderCandidates(); showCriteria(); clearResults("Sample role and candidates loaded. Click Rank candidates to see the results."); }
function parseCsvLine(line) { const values = [], pattern = /("(?:[^"]|"")*"|[^,]*)(?:,|$)/g; let match; while ((match = pattern.exec(line)) !== null) { values.push(match[1].replace(/^"|"$/g, "").replaceAll('""', '"')); if (match.index + match[0].length === line.length) break; } return values; }
function importCsv(event) { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = loadEvent => { const lines = loadEvent.target.result.trim().split(/\r?\n/), headers = parseCsvLine(lines.shift()).map(header => header.toLowerCase()); const nameIndex = headers.indexOf("candidate_name"), resumeIndex = headers.indexOf("resume_text"); if (nameIndex < 0 || resumeIndex < 0) { alert("Your CSV needs candidate_name and resume_text columns."); return; } const imported = lines.map(parseCsvLine).filter(row => row[nameIndex] && row[resumeIndex]).map(row => ({ name: row[nameIndex], resume: row[resumeIndex] })); candidates.push(...imported); renderCandidates(); clearResults(`${imported.length} candidates imported. Click Rank candidates to see the results.`); alert(`${imported.length} candidates imported successfully.`); }; reader.readAsText(file); event.target.value = ""; }
function resetData() { if (!confirm("Reset the job description, candidates, and results?")) return; candidates = []; document.getElementById("jobDescription").value = ""; document.getElementById("candidateName").value = ""; document.getElementById("resumeText").value = ""; document.getElementById("criteria").classList.add("hidden"); document.getElementById("resultFilter").value = ""; renderCandidates(); clearResults("Add a role and one or more candidates to see the comparison."); }
function exportCsv() { if (!lastRanked.length) return; const shown = filteredResults(); const rows = [["Rank", "Candidate", "Match score", "Matched skills", "Missing skills", "Stated experience"], ...shown.map(c => [lastRanked.indexOf(c) + 1, c.name, `${c.value}%`, c.found.join("; "), c.missing.join("; "), c.experience])]; const csv = rows.map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = "talentlens-candidate-ranking.csv"; link.click(); URL.revokeObjectURL(link.href); }
async function extractPdfText(file) { const buffer = await file.arrayBuffer(); const pdf = await pdfjsLib.getDocument({ data: buffer }).promise; let fullText = ""; for (let pageNumber = 1; pageNumber <= pdf.numPages; pageNumber++) { const page = await pdf.getPage(pageNumber); const content = await page.getTextContent(); fullText += content.items.map(item => item.str).join(" ") + "\n"; } return fullText.trim(); }
function handleResumeFile(event) { const file = event.target.files[0]; if (!file) return; const status = document.getElementById("resumeFileStatus"); const isPdf = file.type === "application/pdf" || file.name.toLowerCase().endsWith(".pdf"); if (isPdf) { status.textContent = "Reading PDF…"; extractPdfText(file).then(pdfText => { document.getElementById("resumeText").value = pdfText || ""; status.textContent = pdfText ? "PDF text loaded. Please check it looks right before adding the candidate." : "Could not find readable text in this PDF—it may be a scanned image."; }).catch(() => { status.textContent = "Could not read this PDF. Try pasting the resume text instead."; }); } else { status.textContent = ""; const reader = new FileReader(); reader.onload = loadEvent => document.getElementById("resumeText").value = loadEvent.target.result; reader.readAsText(file); } }
document.getElementById("analyzeJob").addEventListener("click", showCriteria); document.getElementById("addCandidate").addEventListener("click", addCandidate); document.getElementById("loadSample").addEventListener("click", loadSample); document.getElementById("resetData").addEventListener("click", resetData); document.getElementById("rankCandidates").addEventListener("click", rankCandidates); document.getElementById("exportCsv").addEventListener("click", exportCsv); document.getElementById("resultFilter").addEventListener("input", () => { if (lastRanked.length) renderResults(); }); document.querySelectorAll(".weight-input").forEach(input => input.addEventListener("input", validWeights)); document.getElementById("resumeFile").addEventListener("change", handleResumeFile); document.getElementById("csvFile").addEventListener("change", importCsv); document.getElementById("minScoreFilter").addEventListener("input", () => { if (lastRanked.length) renderResults(); }); document.getElementById("minExperienceFilter").addEventListener("input", () => { if (lastRanked.length) renderResults(); });
