const skillBank = ["python","sql","excel","power bi","tableau","javascript","html","css","react","java","c++","machine learning","data analysis","data visualization","communication","leadership","project management","aws","azure","docker","git","figma","salesforce","marketing","accounting","finance","recruitment","customer service"];
const educationWords = ["bachelor","b.tech","b.e.","bsc","master","m.tech","mba","msc","phd","degree"];
let candidates = [];

function text(id) { return document.getElementById(id).value.trim(); }
function findTerms(value, terms) { const lower = value.toLowerCase(); return terms.filter(term => lower.includes(term)); }
function jobCriteria() { const jd = text("jobDescription"); return { skills:findTerms(jd, skillBank), education:findTerms(jd, educationWords), years:(jd.match(/\b(\d+)\+?\s*(?:years?|yrs?)/i)||[])[1] }; }
function showCriteria() { const criteria = jobCriteria(), target=document.getElementById("criteria"); if(!text("jobDescription")){ alert("Please paste a job description first."); return; } target.classList.remove("hidden"); target.innerHTML=`<strong>Criteria found:</strong><br>${criteria.skills.length ? criteria.skills.map(s=>`<span class="tag">${s}</span>`).join("") : "No common skills found—try adding skill names."}${criteria.years ? `<span class="tag">${criteria.years}+ years experience</span>` : ""}`; }
function addCandidate() { const name=text("candidateName"), resume=text("resumeText"); if(!name||!resume){ alert("Please enter both a candidate name and resume text."); return; } candidates.push({name,resume}); document.getElementById("candidateName").value=""; document.getElementById("resumeText").value=""; renderCandidates(); }
function renderCandidates() { const list=document.getElementById("candidateList"); list.innerHTML=candidates.map((c,i)=>`<div class="candidate-chip"><span>${c.name}</span><button class="remove" onclick="removeCandidate(${i})">Remove</button></div>`).join(""); }
function removeCandidate(i){ candidates.splice(i,1); renderCandidates(); document.getElementById("results").innerHTML="Candidates changed. Click Rank candidates again."; }
function score(candidate, criteria) { const found=findTerms(candidate.resume,criteria.skills); const skillScore=criteria.skills.length ? found.length/criteria.skills.length*70 : 0; const educationScore=criteria.education.length && findTerms(candidate.resume,criteria.education).length ? 15 : 0; const listedYears=(candidate.resume.match(/\b(\d+)\+?\s*(?:years?|yrs?)/i)||[])[1]; const experienceScore=criteria.years && listedYears ? Math.min(Number(listedYears)/Number(criteria.years),1)*15 : (criteria.years ? 0 : 15); return {value:Math.round(skillScore+educationScore+experienceScore),found}; }
function rankCandidates() { const criteria=jobCriteria(), output=document.getElementById("results"); if(!text("jobDescription")||!candidates.length){ alert("Add a job description and at least one candidate first."); return; } const ranked=candidates.map(c=>({...c,...score(c,criteria)})).sort((a,b)=>b.value-a.value); output.classList.remove("empty-state"); output.innerHTML=ranked.map((c,i)=>`<div class="result-row"><div class="rank">#${i+1}</div><div><strong>${c.name}</strong><div class="bar"><div class="fill" style="width:${c.value}%"></div></div><div class="match">Matched: ${c.found.length ? c.found.join(", ") : "No listed skills"}</div></div><div class="score">${c.value}% match</div></div>`).join("")+`<div class="fairness"><strong>Human review required:</strong> This is a simple keyword comparison, not an automated hiring decision. Check each resume fairly, consider transferable skills, and never use protected personal characteristics to rank people.</div>`; }
document.getElementById("analyzeJob").addEventListener("click",showCriteria); document.getElementById("addCandidate").addEventListener("click",addCandidate); document.getElementById("rankCandidates").addEventListener("click",rankCandidates); document.getElementById("resumeFile").addEventListener("change",e=>{ const file=e.target.files[0]; if(!file)return; const reader=new FileReader(); reader.onload=event=>document.getElementById("resumeText").value=event.target.result; reader.readAsText(file); });
